---
version: "2.0"

services:
  backend:
    image: pratyushkumar43/disaster-backend:latest
    expose:
      - port: 10000
        as: 80
        to:
          - global: true
    env:
      - "NODE_ENV=production"
      - "PORT=10000"
      - "MONGODB_URI=mongodb+srv://your-username:your-password@your-cluster.mongodb.net/disaster-management"
      - "WEATHER_API_KEY=your-openweather-api-key"
      - "JWT_SECRET=your-jwt-secret"
      - "CORS_ORIGIN=https://disaster-frontend.akash.network"
    resources:
      cpu:
        units: 1.0
      memory:
        size: 1Gi
      storage:
        size: 2Gi
    
  frontend:
    image: pratyushkumar43/disaster-frontend:latest
    expose:
      - port: 3000
        as: 80
        to:
          - global: true
    env:
      - "NODE_ENV=production"
      - "NEXT_PUBLIC_API_URL=https://disaster-backend.akash.network"
      - "PORT=3000"
      - "HOSTNAME=0.0.0.0"
    resources:
      cpu:
        units: 0.5
      memory:
        size: 512Mi
      storage:
        size: 1Gi

profiles:
  compute:
    backend:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 1Gi
        storage:
          - size: 2Gi
    frontend:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          - size: 1Gi

  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        backend:
          denom: uakt
          amount: 1000
        frontend:
          denom: uakt
          amount: 500

deployment:
  backend:
    dcloud:
      profile: backend
      count: 1
  frontend:
    dcloud:
      profile: frontend
      count: 1
